
name: Discord Message Notify

on:
  pull_request:
    branches: [ develop ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Message Notify
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub Bot"
        title: "${{ github.event.pull_request.title }}"
        description: "${{ github.event.pull_request.body }}"
        url: "${{ github.event.pull_request.html_url }}"
